# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17cdf08d654012ff1f5fd39db4f71e41d2650c155a446b3cdf32bd3f662189d208f64a8168ddcc62d4e82504466e688d4d0c029f1f59fbb38873937abae3ed26

test:
  secret_key_base: 00be07518bc7306eb4c7d0747a1478d27336538e967335698172c89c931dea25c2c58093b7fe8937d8d9cf615eb3361b1e67b1583e1fa96f54b5ee55a09643fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
